version: '3.0'

services:
  verdaccio:
    container_name: verdaccio
    image:  verdaccio/verdaccio:latest
    volumes:
      - ./conf:/verdaccio/conf
      - ./storage:/verdaccio/storage
    network_mode: bridge
    ports:
      - 4873:4873
    expose:
      - 4873
